#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

zynq_drm-y := zynq_drm_drv.o
zynq_drm-y += zynq_cresample.o zynq_rgb2yuv.o

obj-$(CONFIG_DRM_ZYNQ) += zynq_drm.o
