/*
 * Xilinx Controls Header
 *
 * Copyright (C) 2013 Xilinx, Inc.
 *
 * Author: Hyun Woo Kwon <hyunk@xilinx.com>
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __XILINX_CONTROLS_H__
#define __XILINX_CONTROLS_H__

#include <linux/v4l2-controls.h>

#define V4L2_CID_XILINX_OFFSET	0xb000
#define V4L2_CID_XILINX_BASE	(V4L2_CID_USER_BASE + V4L2_CID_XILINX_OFFSET)

/*
 * Private Controls for Xilinx Video IPs
 */

/* TODO: use subdev id instead of hard coded base for multiple instances */
/* tpg */
#define V4L2_CID_XILINX_TPG			(V4L2_CID_XILINX_BASE + 0x000)
#define V4L2_CID_XILINX_TPG_CROSS_HAIRS		(V4L2_CID_XILINX_TPG + 2)
#define V4L2_CID_XILINX_TPG_MOVING_BOX		(V4L2_CID_XILINX_TPG + 3)
#define V4L2_CID_XILINX_TPG_COLOR_MASK		(V4L2_CID_XILINX_TPG + 4)
#define V4L2_CID_XILINX_TPG_STUCK_PIXEL		(V4L2_CID_XILINX_TPG + 5)
#define V4L2_CID_XILINX_TPG_NOISE		(V4L2_CID_XILINX_TPG + 6)
#define V4L2_CID_XILINX_TPG_MOTION		(V4L2_CID_XILINX_TPG + 7)
#define V4L2_CID_XILINX_TPG_MOTION_SPEED	(V4L2_CID_XILINX_TPG + 8)
#define V4L2_CID_XILINX_TPG_CROSS_HAIR_ROW	(V4L2_CID_XILINX_TPG + 9)
#define V4L2_CID_XILINX_TPG_CROSS_HAIR_COLUMN	(V4L2_CID_XILINX_TPG + 10)
#define V4L2_CID_XILINX_TPG_ZPLATE_HOR_START	(V4L2_CID_XILINX_TPG + 11)
#define V4L2_CID_XILINX_TPG_ZPLATE_HOR_SPEED	(V4L2_CID_XILINX_TPG + 12)
#define V4L2_CID_XILINX_TPG_ZPLATE_VER_START	(V4L2_CID_XILINX_TPG + 13)
#define V4L2_CID_XILINX_TPG_ZPLATE_VER_SPEED	(V4L2_CID_XILINX_TPG + 14)
#define V4L2_CID_XILINX_TPG_BOX_SIZE		(V4L2_CID_XILINX_TPG + 15)
#define V4L2_CID_XILINX_TPG_BOX_COLOR		(V4L2_CID_XILINX_TPG + 16)
#define V4L2_CID_XILINX_TPG_STUCK_PIXEL_THRESH	(V4L2_CID_XILINX_TPG + 17)
#define V4L2_CID_XILINX_TPG_NOISE_GAIN		(V4L2_CID_XILINX_TPG + 18)
#define V4L2_CID_XILINX_TPG_BAYER_PHASE		(V4L2_CID_XILINX_TPG + 19)

/* ccm */
#define V4L2_CID_XILINX_CCM			(V4L2_CID_XILINX_BASE + 0x020)
#define V4L2_CID_XILINX_CCM_COEFF11		(V4L2_CID_XILINX_CCM + 1)
#define V4L2_CID_XILINX_CCM_COEFF12		(V4L2_CID_XILINX_CCM + 2)
#define V4L2_CID_XILINX_CCM_COEFF13		(V4L2_CID_XILINX_CCM + 3)
#define V4L2_CID_XILINX_CCM_COEFF21		(V4L2_CID_XILINX_CCM + 4)
#define V4L2_CID_XILINX_CCM_COEFF22		(V4L2_CID_XILINX_CCM + 5)
#define V4L2_CID_XILINX_CCM_COEFF23		(V4L2_CID_XILINX_CCM + 6)
#define V4L2_CID_XILINX_CCM_COEFF31		(V4L2_CID_XILINX_CCM + 7)
#define V4L2_CID_XILINX_CCM_COEFF32		(V4L2_CID_XILINX_CCM + 8)
#define V4L2_CID_XILINX_CCM_COEFF33		(V4L2_CID_XILINX_CCM + 9)
#define V4L2_CID_XILINX_CCM_RED_OFFSET		(V4L2_CID_XILINX_CCM + 10)
#define V4L2_CID_XILINX_CCM_GREEN_OFFSET	(V4L2_CID_XILINX_CCM + 11)
#define V4L2_CID_XILINX_CCM_BLUE_OFFSET		(V4L2_CID_XILINX_CCM + 12)
#define V4L2_CID_XILINX_CCM_CLIP		(V4L2_CID_XILINX_CCM + 13)
#define V4L2_CID_XILINX_CCM_CLAMP		(V4L2_CID_XILINX_CCM + 14)

/* cfa */
#define V4L2_CID_XILINX_CFA			(V4L2_CID_XILINX_BASE + 0x040)
#define V4L2_CID_XILINX_CFA_BAYER		(V4L2_CID_XILINX_CFA + 1)

/* cresample */
#define V4L2_CID_XILINX_CRESAMPLE		(V4L2_CID_XILINX_BASE + 0x060)
#define V4L2_CID_XILINX_CRESAMPLE_FIELD_PARITY	(V4L2_CID_XILINX_CRESAMPLE + 1)
#define V4L2_CID_XILINX_CRESAMPLE_CHROMA_PARITY	(V4L2_CID_XILINX_CRESAMPLE + 2)

/* enhance */
#define V4L2_CID_XILINX_ENHANCE			(V4L2_CID_XILINX_BASE + 0x080)
#define V4L2_CID_XILINX_ENHANCE_NOISE_THRESHOLD	(V4L2_CID_XILINX_ENHANCE + 1)
#define V4L2_CID_XILINX_ENHANCE_STRENGTH	(V4L2_CID_XILINX_ENHANCE + 2)
#define V4L2_CID_XILINX_ENHANCE_HALO_SUPPRESS	(V4L2_CID_XILINX_ENHANCE + 3)

/* gamma */
#define V4L2_CID_XILINX_GAMMA			(V4L2_CID_XILINX_BASE + 0x0a0)
#define V4L2_CID_XILINX_GAMMA_SWITCH_LUT	(V4L2_CID_XILINX_GAMMA + 1)
#define V4L2_CID_XILINX_GAMMA_UPDATE_LUT	(V4L2_CID_XILINX_GAMMA + 2)

/* rgb2ycrcb */
#define V4L2_CID_XILINX_RGB2YUV			(V4L2_CID_XILINX_BASE + 0x0c0)
#define V4L2_CID_XILINX_RGB2YUV_YMAX		(V4L2_CID_XILINX_RGB2YUV + 1)
#define V4L2_CID_XILINX_RGB2YUV_YMIN		(V4L2_CID_XILINX_RGB2YUV + 2)
#define V4L2_CID_XILINX_RGB2YUV_CBMAX		(V4L2_CID_XILINX_RGB2YUV + 3)
#define V4L2_CID_XILINX_RGB2YUV_CBMIN		(V4L2_CID_XILINX_RGB2YUV + 4)
#define V4L2_CID_XILINX_RGB2YUV_CRMAX		(V4L2_CID_XILINX_RGB2YUV + 5)
#define V4L2_CID_XILINX_RGB2YUV_CRMIN		(V4L2_CID_XILINX_RGB2YUV + 6)
#define V4L2_CID_XILINX_RGB2YUV_YOFFSET		(V4L2_CID_XILINX_RGB2YUV + 7)
#define V4L2_CID_XILINX_RGB2YUV_CBOFFSET	(V4L2_CID_XILINX_RGB2YUV + 8)
#define V4L2_CID_XILINX_RGB2YUV_CROFFSET	(V4L2_CID_XILINX_RGB2YUV + 9)
#define V4L2_CID_XILINX_RGB2YUV_ACOEF		(V4L2_CID_XILINX_RGB2YUV + 10)
#define V4L2_CID_XILINX_RGB2YUV_BCOEF		(V4L2_CID_XILINX_RGB2YUV + 11)
#define V4L2_CID_XILINX_RGB2YUV_CCOEF		(V4L2_CID_XILINX_RGB2YUV + 12)
#define V4L2_CID_XILINX_RGB2YUV_DCOEF		(V4L2_CID_XILINX_RGB2YUV + 13)

/* spc(dpc) */
#define V4L2_CID_XILINX_SPC			(V4L2_CID_XILINX_BASE + 0x0e0)
#define V4L2_CID_XILINX_SPC_TEMPORAL		(V4L2_CID_XILINX_SPC + 1)
#define V4L2_CID_XILINX_SPC_SPATIAL		(V4L2_CID_XILINX_SPC + 2)
#define V4L2_CID_XILINX_SPC_PIXEL_AGE		(V4L2_CID_XILINX_SPC + 3)

/* stats */
#define V4L2_CID_XILINX_STATS			(V4L2_CID_XILINX_BASE + 0x100)
#define V4L2_CID_XILINX_STATS_HMAX0		(V4L2_CID_XILINX_STATS + 1)
#define V4L2_CID_XILINX_STATS_HMAX1		(V4L2_CID_XILINX_STATS + 2)
#define V4L2_CID_XILINX_STATS_HMAX2		(V4L2_CID_XILINX_STATS + 3)
#define V4L2_CID_XILINX_STATS_VMAX0		(V4L2_CID_XILINX_STATS + 4)
#define V4L2_CID_XILINX_STATS_VMAX1		(V4L2_CID_XILINX_STATS + 5)
#define V4L2_CID_XILINX_STATS_VMAX2		(V4L2_CID_XILINX_STATS + 6)
#define V4L2_CID_XILINX_STATS_HIST_ZOOM_FACTOR	(V4L2_CID_XILINX_STATS + 7)
#define V4L2_CID_XILINX_STATS_RGB_HIST_ZONE_EN	(V4L2_CID_XILINX_STATS + 8)
#define V4L2_CID_XILINX_STATS_YCC_HIST_ZONE_EN	(V4L2_CID_XILINX_STATS + 9)
#define V4L2_CID_XILINX_STATS_ZONE_ADDR		(V4L2_CID_XILINX_STATS + 10)
#define V4L2_CID_XILINX_STATS_COLOR_ADDR	(V4L2_CID_XILINX_STATS + 11)
#define V4L2_CID_XILINX_STATS_HIST_ADDR		(V4L2_CID_XILINX_STATS + 12)
#define V4L2_CID_XILINX_STATS_ADDR_VALID	(V4L2_CID_XILINX_STATS + 13)

/* scaler */
#define V4L2_CID_XILINX_SCALER			(V4L2_CID_XILINX_BASE + 0x120)
#define V4L2_CID_XILINX_SCALER_HAPERTURE_START	(V4L2_CID_XILINX_SCALER + 1)
#define V4L2_CID_XILINX_SCALER_HAPERTURE_END	(V4L2_CID_XILINX_SCALER + 2)
#define V4L2_CID_XILINX_SCALER_VAPERTURE_START	(V4L2_CID_XILINX_SCALER + 3)
#define V4L2_CID_XILINX_SCALER_VAPERTURE_END	(V4L2_CID_XILINX_SCALER + 4)

#endif /* __XILINX_CONTROLS_H__ */
